version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - redis
      - postgres
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    deploy:
      replicas: 3
    depends_on:
      - redis
      - postgres
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: taskqueue
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskqueue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: